workspace:
  base: /go
  path: src/github.com/fbcbarbosa/runes

pipeline:
  deps:
    image: golang:1.8-alpine
    commands:
      - go get -t ./...
    when:
      branch: $DRONE_BRANCH
  
  test:
    image: golang:1.8-alpine
    commands:
      - go test .
    when:
      branch: ${DRONE_BRANCH}

  build:
    image: golang:1.8-alpine
    commands:
      - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo
    when:
      branch: $${DRONE_BRANCH}

